export type HskLevel = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9

export type Word = {
  hanzi: string
  pinyin: string
  meaning: string
  level: HskLevel
  category: string
}

type Row = [string, string, string, string]

const hsk1: Row[] = [
  ['我', 'wǒ', 'tôi, tớ', 'Đại từ'],
  ['你', 'nǐ', 'bạn, cậu', 'Đại từ'],
  ['他', 'tā', 'anh ấy', 'Đại từ'],
  ['她', 'tā', 'cô ấy', 'Đại từ'],
  ['我们', 'wǒmen', 'chúng tôi', 'Đại từ'],
  ['好', 'hǎo', 'tốt, khỏe', 'Tính từ'],
  ['大', 'dà', 'to, lớn', 'Tính từ'],
  ['小', 'xiǎo', 'nhỏ, bé', 'Tính từ'],
  ['多', 'duō', 'nhiều', 'Tính từ'],
  ['少', 'shǎo', 'ít', 'Tính từ'],
  ['热', 'rè', 'nóng', 'Tính từ'],
  ['冷', 'lěng', 'lạnh', 'Tính từ'],
  ['是', 'shì', 'là', 'Động từ'],
  ['爱', 'ài', 'yêu', 'Động từ'],
  ['吃', 'chī', 'ăn', 'Động từ'],
  ['喝', 'hē', 'uống', 'Động từ'],
  ['看', 'kàn', 'xem, nhìn', 'Động từ'],
  ['说', 'shuō', 'nói', 'Động từ'],
  ['读', 'dú', 'đọc', 'Động từ'],
  ['写', 'xiě', 'viết', 'Động từ'],
  ['去', 'qù', 'đi', 'Động từ'],
  ['来', 'lái', 'đến, tới', 'Động từ'],
  ['买', 'mǎi', 'mua', 'Động từ'],
  ['水', 'shuǐ', 'nước', 'Đồ ăn uống'],
  ['茶', 'chá', 'trà', 'Đồ ăn uống'],
  ['米饭', 'mǐfàn', 'cơm', 'Đồ ăn uống'],
  ['苹果', 'píngguǒ', 'quả táo', 'Đồ ăn uống'],
  ['猫', 'māo', 'con mèo', 'Danh từ'],
  ['狗', 'gǒu', 'con chó', 'Danh từ'],
  ['人', 'rén', 'người', 'Danh từ'],
  ['中国', 'Zhōngguó', 'Trung Quốc', 'Danh từ'],
  ['书', 'shū', 'sách', 'Danh từ'],
  ['钱', 'qián', 'tiền', 'Danh từ'],
  ['电脑', 'diànnǎo', 'máy tính', 'Danh từ'],
  ['家', 'jiā', 'nhà, gia đình', 'Danh từ'],
  ['学校', 'xuéxiào', 'trường học', 'Danh từ'],
  ['天气', 'tiānqì', 'thời tiết', 'Danh từ'],
  ['学生', 'xuésheng', 'học sinh', 'Nghề nghiệp'],
  ['老师', 'lǎoshī', 'giáo viên', 'Nghề nghiệp'],
  ['医生', 'yīshēng', 'bác sĩ', 'Nghề nghiệp'],
  ['朋友', 'péngyou', 'bạn bè', 'Gia đình'],
  ['妈妈', 'māma', 'mẹ', 'Gia đình'],
  ['爸爸', 'bàba', 'bố', 'Gia đình'],
  ['一', 'yī', 'một', 'Số đếm'],
  ['二', 'èr', 'hai', 'Số đếm'],
  ['三', 'sān', 'ba', 'Số đếm'],
  ['十', 'shí', 'mười', 'Số đếm'],
  ['今天', 'jīntiān', 'hôm nay', 'Thời gian'],
  ['明天', 'míngtiān', 'ngày mai', 'Thời gian'],
  ['昨天', 'zuótiān', 'hôm qua', 'Thời gian'],
  ['谢谢', 'xièxie', 'cảm ơn', 'Giao tiếp'],
  ['再见', 'zàijiàn', 'tạm biệt', 'Giao tiếp'],
  ['对不起', 'duìbuqǐ', 'xin lỗi', 'Giao tiếp'],
  ['不', 'bù', 'không', 'Giao tiếp'],
  ['你好', 'nǐhǎo', 'xin chào', 'Giao tiếp'],
  ['请', 'qǐng', 'mời, xin', 'Giao tiếp'],
  ['叫', 'jiào', 'gọi, tên là', 'Động từ'],
  ['什么', 'shénme', 'cái gì', 'Giao tiếp'],
  ['吗', 'ma', 'tiểu từ nghi vấn', 'Giao tiếp'],
  ['很', 'hěn', 'rất', 'Phó từ'],
  ['也', 'yě', 'cũng', 'Phó từ'],
  ['在', 'zài', 'ở, đang', 'Động từ'],
  ['有', 'yǒu', 'có', 'Động từ'],
  ['想', 'xiǎng', 'muốn, nghĩ', 'Động từ'],
  ['会', 'huì', 'biết (kỹ năng)', 'Động từ'],
  ['现在', 'xiànzài', 'bây giờ', 'Thời gian'],
  ['年', 'nián', 'năm', 'Thời gian'],
  ['月', 'yuè', 'tháng', 'Thời gian'],
]

const hsk2: Row[] = [
  ['唱歌', 'chànggē', 'hát', 'Sở thích'],
  ['跳舞', 'tiàowǔ', 'nhảy múa', 'Sở thích'],
  ['旅游', 'lǚyóu', 'du lịch', 'Sở thích'],
  ['运动', 'yùndòng', 'thể thao, vận động', 'Sở thích'],
  ['游泳', 'yóuyǒng', 'bơi lội', 'Sở thích'],
  ['跑步', 'pǎobù', 'chạy bộ', 'Sở thích'],
  ['咖啡', 'kāfēi', 'cà phê', 'Đồ ăn uống'],
  ['牛奶', 'niúnǎi', 'sữa bò', 'Đồ ăn uống'],
  ['鸡蛋', 'jīdàn', 'trứng gà', 'Đồ ăn uống'],
  ['鱼', 'yú', 'cá', 'Đồ ăn uống'],
  ['西瓜', 'xīguā', 'dưa hấu', 'Đồ ăn uống'],
  ['公司', 'gōngsī', 'công ty', 'Địa điểm'],
  ['机场', 'jīchǎng', 'sân bay', 'Địa điểm'],
  ['医院', 'yīyuàn', 'bệnh viện', 'Địa điểm'],
  ['房间', 'fángjiān', 'căn phòng', 'Địa điểm'],
  ['手机', 'shǒujī', 'điện thoại di động', 'Danh từ'],
  ['眼睛', 'yǎnjing', 'mắt', 'Danh từ'],
  ['生日', 'shēngrì', 'sinh nhật', 'Danh từ'],
  ['快乐', 'kuàilè', 'vui vẻ', 'Tính từ'],
  ['高兴', 'gāoxìng', 'vui mừng', 'Tính từ'],
  ['漂亮', 'piàoliang', 'xinh đẹp', 'Tính từ'],
  ['便宜', 'piányi', 'rẻ', 'Tính từ'],
  ['贵', 'guì', 'đắt', 'Tính từ'],
  ['远', 'yuǎn', 'xa', 'Tính từ'],
  ['近', 'jìn', 'gần', 'Tính từ'],
  ['准备', 'zhǔnbèi', 'chuẩn bị', 'Động từ'],
  ['帮助', 'bāngzhù', 'giúp đỡ', 'Động từ'],
  ['介绍', 'jièshào', 'giới thiệu', 'Động từ'],
  ['觉得', 'juéde', 'cảm thấy', 'Động từ'],
  ['希望', 'xīwàng', 'hy vọng', 'Động từ'],
  ['早上', 'zǎoshang', 'buổi sáng', 'Thời gian'],
  ['晚上', 'wǎnshang', 'buổi tối', 'Thời gian'],
  ['丈夫', 'zhàngfu', 'chồng', 'Gia đình'],
  ['妻子', 'qīzi', 'vợ', 'Gia đình'],
  ['孩子', 'háizi', 'con cái, trẻ em', 'Gia đình'],
]

const hsk3: Row[] = [
  ['地图', 'dìtú', 'bản đồ', 'Danh từ'],
  ['环境', 'huánjìng', 'môi trường', 'Danh từ'],
  ['文化', 'wénhuà', 'văn hóa', 'Danh từ'],
  ['历史', 'lìshǐ', 'lịch sử', 'Danh từ'],
  ['世界', 'shìjiè', 'thế giới', 'Danh từ'],
  ['城市', 'chéngshì', 'thành phố', 'Danh từ'],
  ['熊猫', 'xióngmāo', 'gấu trúc', 'Danh từ'],
  ['冰箱', 'bīngxiāng', 'tủ lạnh', 'Danh từ'],
  ['电梯', 'diàntī', 'thang máy', 'Danh từ'],
  ['会议', 'huìyì', 'cuộc họp', 'Danh từ'],
  ['声音', 'shēngyīn', 'âm thanh', 'Danh từ'],
  ['音乐', 'yīnyuè', 'âm nhạc', 'Danh từ'],
  ['礼物', 'lǐwù', 'quà tặng', 'Danh từ'],
  ['节日', 'jiérì', 'ngày lễ', 'Danh từ'],
  ['习惯', 'xíguàn', 'thói quen', 'Danh từ'],
  ['经常', 'jīngcháng', 'thường xuyên', 'Phó từ'],
  ['健康', 'jiànkāng', 'khỏe mạnh', 'Tính từ'],
  ['聪明', 'cōngming', 'thông minh', 'Tính từ'],
  ['认真', 'rènzhēn', 'nghiêm túc, chăm chỉ', 'Tính từ'],
  ['简单', 'jiǎndān', 'đơn giản', 'Tính từ'],
  ['满意', 'mǎnyì', 'hài lòng', 'Tính từ'],
  ['着急', 'zháojí', 'sốt ruột, lo lắng', 'Tính từ'],
  ['担心', 'dānxīn', 'lo lắng', 'Động từ'],
  ['练习', 'liànxí', 'luyện tập', 'Động từ'],
  ['复习', 'fùxí', 'ôn tập', 'Động từ'],
  ['解决', 'jiějué', 'giải quyết', 'Động từ'],
  ['选择', 'xuǎnzé', 'lựa chọn', 'Động từ'],
  ['决定', 'juédìng', 'quyết định', 'Động từ'],
  ['照顾', 'zhàogù', 'chăm sóc', 'Động từ'],
  ['关心', 'guānxīn', 'quan tâm', 'Động từ'],
]

const hsk4: Row[] = [
  ['政策', 'zhèngcè', 'chính sách', 'Danh từ'],
  ['经济', 'jīngjì', 'kinh tế', 'Danh từ'],
  ['发展', 'fāzhǎn', 'phát triển', 'Động từ'],
  ['影响', 'yǐngxiǎng', 'ảnh hưởng', 'Động từ'],
  ['讨论', 'tǎolùn', 'thảo luận', 'Động từ'],
  ['建议', 'jiànyì', 'đề xuất, gợi ý', 'Động từ'],
  ['完成', 'wánchéng', 'hoàn thành', 'Động từ'],
  ['提供', 'tígōng', 'cung cấp', 'Động từ'],
  ['接受', 'jiēshòu', 'chấp nhận', 'Động từ'],
  ['拒绝', 'jùjué', 'từ chối', 'Động từ'],
  ['重要', 'zhòngyào', 'quan trọng', 'Tính từ'],
  ['主要', 'zhǔyào', 'chính', 'Tính từ'],
  ['必要', 'bìyào', 'cần thiết', 'Tính từ'],
  ['可能', 'kěnéng', 'có thể', 'Tính từ'],
  ['值得', 'zhídé', 'đáng', 'Tính từ'],
  ['显然', 'xiǎnrán', 'hiển nhiên', 'Phó từ'],
  ['究竟', 'jiūjìng', 'rốt cuộc', 'Phó từ'],
  ['实际上', 'shíjìshàng', 'thực tế', 'Phó từ'],
  ['无论如何', 'wúlùn rúhé', 'dù sao', 'Phó từ'],
  ['由此可见', 'yóucǐ kějiàn', 'từ đó có thể thấy', 'Phó từ'],
]

const hsk5: Row[] = [
  ['意识', 'yìshí', 'ý thức', 'Danh từ'],
  ['概念', 'gàiniàn', 'khái niệm', 'Danh từ'],
  ['理论', 'lǐlùn', 'lý thuyết', 'Danh từ'],
  ['观点', 'guāndiǎn', 'quan điểm', 'Danh từ'],
  ['态度', 'tàidù', 'thái độ', 'Danh từ'],
  ['立场', 'lìchǎng', 'lập trường', 'Danh từ'],
  ['原则', 'yuánzé', 'nguyên tắc', 'Danh từ'],
  ['标准', 'biāozhǔn', 'tiêu chuẩn', 'Danh từ'],
  ['现象', 'xiànxiàng', 'hiện tượng', 'Danh từ'],
  ['本质', 'běnzhì', 'bản chất', 'Danh từ'],
  ['依靠', 'yīkào', 'dựa vào', 'Động từ'],
  ['依赖', 'yīlài', 'phụ thuộc', 'Động từ'],
  ['维持', 'wéichí', 'duy trì', 'Động từ'],
  ['保持', 'bǎochí', 'giữ gìn', 'Động từ'],
  ['持续', 'chíxù', 'tiếp tục', 'Động từ'],
  ['促进', 'cùjìn', 'thúc đẩy', 'Động từ'],
  ['推动', 'tuīdòng', 'đẩy mạnh', 'Động từ'],
  ['发挥', 'fāhuī', 'phát huy', 'Động từ'],
  ['强调', 'qiángdiào', 'nhấn mạnh', 'Động từ'],
  ['重视', 'zhòngshì', 'coi trọng', 'Động từ'],
]

const hsk6: Row[] = [
  ['领域', 'lǐngyù', 'lĩnh vực', 'Danh từ'],
  ['范围', 'fànwéi', 'phạm vi', 'Danh từ'],
  ['背景', 'bèijǐng', 'bối cảnh', 'Danh từ'],
  ['环境', 'huánjìng', 'môi trường', 'Danh từ'],
  ['条件', 'tiáojiàn', 'điều kiện', 'Danh từ'],
  ['因素', 'yīnsù', 'yếu tố', 'Danh từ'],
  ['特征', 'tèzhēng', 'đặc điểm', 'Danh từ'],
  ['特点', 'tèdiǎn', 'đặc tính', 'Danh từ'],
  ['优势', 'yōushì', 'lợi thế', 'Danh từ'],
  ['劣势', 'lièshì', 'nhược điểm', 'Danh từ'],
  ['限制', 'xiànzhì', 'hạn chế', 'Động từ'],
  ['约束', 'yuēshù', 'ràng buộc', 'Động từ'],
  ['控制', 'kòngzhì', 'kiểm soát', 'Động từ'],
  ['管理', 'guǎnlǐ', 'quản lý', 'Động từ'],
  ['处理', 'chǔlǐ', 'xử lý', 'Động từ'],
  ['操作', 'cāozuò', 'vận hành', 'Động từ'],
  ['实施', 'shíshī', 'thực hiện', 'Động từ'],
  ['执行', 'zhíxíng', 'thi hành', 'Động từ'],
  ['落实', 'luòshí', 'thực thi', 'Động từ'],
  ['推进', 'tuījìn', 'thúc tiến', 'Động từ'],
]

const hsk7: Row[] = [
  ['机制', 'jīzhì', 'cơ chế', 'Danh từ'],
  ['体系', 'tǐxì', 'hệ thống', 'Danh từ'],
  ['结构', 'jiégòu', 'cấu trúc', 'Danh từ'],
  ['框架', 'kuàngjià', 'khung', 'Danh từ'],
  ['模式', 'móshì', 'mô hình', 'Danh từ'],
  ['途径', 'tújìng', 'con đường', 'Danh từ'],
  ['手段', 'shǒuduàn', 'biện pháp', 'Danh từ'],
  ['方法', 'fāngfǎ', 'phương pháp', 'Danh từ'],
  ['策略', 'cèlüè', 'chiến lược', 'Danh từ'],
  ['方案', 'fāngàn', 'kế hoạch', 'Danh từ'],
  ['构建', 'gòujiàn', 'xây dựng', 'Động từ'],
  ['建立', 'jiànlì', 'thiết lập', 'Động từ'],
  ['形成', 'xíngchéng', 'hình thành', 'Động từ'],
  ['产生', 'chǎnshēng', 'sinh ra', 'Động từ'],
  ['引起', 'yǐnqǐ', 'gây ra', 'Động từ'],
  ['导致', 'dǎozhì', 'dẫn đến', 'Động từ'],
  ['造成', 'zàochéng', 'tạo ra', 'Động từ'],
  ['带来', 'dàilái', 'mang lại', 'Động từ'],
  ['获得', 'huòdé', 'có được', 'Động từ'],
  ['取得', 'qǔdé', 'thu được', 'Động từ'],
]

const hsk8: Row[] = [
  ['意识形态', 'yìshí xíngtài', 'ý thức hệ', 'Danh từ'],
  ['政治制度', 'zhèngzhì zhìdù', 'chế độ chính trị', 'Danh từ'],
  ['经济体制', 'jīngjì tǐzhì', 'hệ thống kinh tế', 'Danh từ'],
  ['社会结构', 'shèhuì jiégòu', 'cấu trúc xã hội', 'Danh từ'],
  ['文化传统', 'wénhuà chuántǒng', 'truyền thống văn hóa', 'Danh từ'],
  ['历史遗产', 'lìshǐ yíchǎn', 'di sản lịch sử', 'Danh từ'],
  ['全球化', 'quánqiúhuà', 'toàn cầu hóa', 'Danh từ'],
  ['信息化', 'xìnxīhuà', 'tin học hóa', 'Danh từ'],
  ['现代化', 'xiàndàihuà', 'hiện đại hóa', 'Danh từ'],
  ['可持续发展', 'kě chíxù fāzhǎn', 'phát triển bền vững', 'Danh từ'],
  ['协调', 'xiétiáo', 'phối hợp', 'Động từ'],
  ['统筹', 'tǒngchóu', 'điều phối', 'Động từ'],
  ['整合', 'zhěnghé', 'tích hợp', 'Động từ'],
  ['优化', 'yōuhuà', 'tối ưu hóa', 'Động từ'],
  ['提升', 'tíshēng', 'nâng cao', 'Động từ'],
  ['改善', 'gǎishàn', 'cải thiện', 'Động từ'],
  ['完善', 'wánshàn', 'hoàn thiện', 'Động từ'],
  ['强化', 'qiánghuà', 'tăng cường', 'Động từ'],
  ['巩固', 'gǒnggù', 'củng cố', 'Động từ'],
  ['深化', 'shēnhuà', 'đẩy sâu', 'Động từ'],
]

const hsk9: Row[] = [
  ['辩证唯物主义', 'biànzhèng wéiwù zhǔyì', 'chủ nghĩa duy vật biện chứng', 'Danh từ'],
  ['历史唯物主义', 'lìshǐ wéiwù zhǔyì', 'chủ nghĩa duy vật lịch sử', 'Danh từ'],
  ['形而上学', 'xíngérshàngxué', 'siêu hình học', 'Danh từ'],
  ['经验主义', 'jīngyàn zhǔyì', 'chủ nghĩa kinh nghiệm', 'Danh từ'],
  ['理性主义', 'lǐxìng zhǔyì', 'chủ nghĩa duy lý', 'Danh từ'],
  ['实用主义', 'shíyòng zhǔyì', 'chủ nghĩa thực dụng', 'Danh từ'],
  ['存在主义', 'cúnzài zhǔyì', 'chủ nghĩa hiện sinh', 'Danh từ'],
  ['后现代主义', 'hòuxiàndài zhǔyì', 'chủ nghĩa hậu hiện đại', 'Danh từ'],
  ['解构主义', 'jiěgòu zhǔyì', 'chủ nghĩa giải cấu trúc', 'Danh từ'],
  ['人文主义', 'rénwén zhǔyì', 'chủ nghĩa nhân văn', 'Danh từ'],
  ['阐释', 'chǎnshì', 'giải thích', 'Động từ'],
  ['剖析', 'pōuxī', 'phân tích', 'Động từ'],
  ['探究', 'tànjiū', 'khám phá', 'Động từ'],
  ['论证', 'lùnzhèng', 'biện luận', 'Động từ'],
  ['推导', 'tuīdǎo', 'suy diễn', 'Động từ'],
  ['演绎', 'yǎnyì', 'diễn dịch', 'Động từ'],
  ['归纳', 'guīnà', 'quy nạp', 'Động từ'],
  ['抽象', 'chōuxiàng', 'trừu tượng hóa', 'Động từ'],
  ['概括', 'gàikuò', 'tổng kết', 'Động từ'],
  ['提炼', 'tíliàn', 'tinh luyện', 'Động từ'],
]

function toWords(rows: Row[], level: HskLevel): Word[] {
  return rows.map(([hanzi, pinyin, meaning, category]) => ({
    hanzi,
    pinyin,
    meaning,
    level,
    category,
  }))
}

export const WORDS: Word[] = [
  ...toWords(hsk1, 1),
  ...toWords(hsk2, 2),
  ...toWords(hsk3, 3),
  ...toWords(hsk4, 4),
  ...toWords(hsk5, 5),
  ...toWords(hsk6, 6),
  ...toWords(hsk7, 7),
  ...toWords(hsk8, 8),
  ...toWords(hsk9, 9),
]

export const LEVELS: { level: HskLevel; title: string; description: string }[] = [
  { level: 1, title: 'HSK 1', description: 'Nhập môn — chào hỏi, số đếm, đời sống cơ bản' },
  { level: 2, title: 'HSK 2', description: 'Sơ cấp — sở thích, mua sắm, địa điểm' },
  { level: 3, title: 'HSK 3', description: 'Trung cấp — cảm xúc, văn hóa, công việc' },
  { level: 4, title: 'HSK 4', description: 'Trung cao cấp — chính sách, kinh tế, phát triển' },
  { level: 5, title: 'HSK 5', description: 'Cao cấp — ý thức, khái niệm, quan điểm' },
  { level: 6, title: 'HSK 6', description: 'Thành thạo — lĩnh vực, quản lý, chiến lược' },
  { level: 7, title: 'HSK 7', description: 'Nâng cao — cơ chế, hệ thống, xây dựng' },
  { level: 8, title: 'HSK 8', description: 'Chuyên sâu — ý thức hệ, toàn cầu hóa' },
  { level: 9, title: 'HSK 9', description: 'Thành thạo — triết học, tư duy trừu tượng' },
]

export function wordsByLevel(level: HskLevel | 'all') {
  return level === 'all' ? WORDS : WORDS.filter((w) => w.level === level)
}

export const CATEGORIES = Array.from(new Set(WORDS.map((w) => w.category)))
